# Generated by Django 6.0.4 on 2026-05-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='content',
            field=models.TextField(blank=True, help_text='Обучающий текст', null=True),
        ),
    ]
