# Generated by Django 6.0.4 on 2026-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Шаблон кода для старта', null=True),
        ),
    ]
