# Generated by Django 6.0.4 on 2026-05-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_starter_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengesubmission',
            unique_together=set(),
        ),
    ]
